version: "3.8"
services:
  # PHP Service
  php:
    image: php:7.4-apache
    container_name: php
    build: .
    volumes:
      - ./:/var/www/html/API-sv
    ports:
      - "8080:80"
    depends_on:
      - mysql

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file: .env
    ports:
      - "3366:3366"

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3366
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - mysql
