version: "3.8"
services:
  # Servicio de PHP con Apache
  php:
    build: .
    container_name: my-php-app
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - APACHE_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN=http://localhost:8080
      - APACHE_HEADER_ACCESS_CONTROL_ALLOW_HEADERS=Content-Type
      - APACHE_HEADER_ACCESS_CONTROL_ALLOW_METHODS=OPTIONS, GET, POST, PUT, DELETE
      - APACHE_HEADER_ACCESS_CONTROL_ALLOW_CREDENTIALS=true

  # Servicio de MySQL
  mysql:
    image: mysql:latest
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: despachos
      MYSQL_USER: gaston
      MYSQL_PASSWORD: blanco
    ports:
      - "3307:3306"
    volumes:
      - ./despachos_dataBase.sql:/docker-entrypoint-initdb.d/despachos_dataBase.sql

  # Servicio de PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - mysql
